server:
  port: 8080
logging:
  level:
    org.springframework.security: DEBUG
  file: my.log
security:
  basic:
    enabled: false
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3308/springboot?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: sEcfOx_pROduct*100%
  jpa:
    hibernate:
      ddl-auto: update

